// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef ui_h
#define ui_h
#include <FL/Fl.H>
#include "matchview.h"
#include <sstream>
#include <FL/Fl_Pack.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Slider.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Check_Button.H>

class UserInterface {
public:
  Fl_Window* make_window();
  MatchView *match_view;
  Fl_Slider *slider_match_length;
private:
  void cb_slider_match_length_i(Fl_Slider*, void*);
  static void cb_slider_match_length(Fl_Slider*, void*);
public:
  Fl_Slider *slider_match_idx;
private:
  void cb_slider_match_idx_i(Fl_Slider*, void*);
  static void cb_slider_match_idx(Fl_Slider*, void*);
public:
  Fl_Output *text_match_length;
  Fl_Output *text_shape_distance;
  Fl_Check_Button *check_show_f1;
private:
  void cb_check_show_f1_i(Fl_Check_Button*, void*);
  static void cb_check_show_f1(Fl_Check_Button*, void*);
public:
  Fl_Check_Button *check_show_f2;
private:
  void cb_check_show_f2_i(Fl_Check_Button*, void*);
  static void cb_check_show_f2(Fl_Check_Button*, void*);
public:
  void set_bucket();
  void set_match();
  void show_f1(bool v);
  void show_f2(bool v);
};
#endif
